.check_doc_links_template: &check_doc_links_template
  stage: post_deploy
  image: $ESP_IDF_DOC_ENV_IMAGE
  tags: [ "build", "amd64", "internet" ]
  only:
    refs:
      - master
      - /^release\/v/
      - /^v\d+\.\d+(\.\d+)?($|-)/
    variables:
      - $BOT_TRIGGER_WITH_LABEL == null
  artifacts:
    when: always
    paths:
      - docs/_build/*/*/*.txt
      - docs/_build/*/*/linkcheck/*.txt
    expire_in: 1 week
  allow_failure: true
  dependencies: []
  script:
    - cd docs
    - ${IDF_PATH}/tools/ci/multirun_with_pyenv.sh -p 3.6.10 pip install -r requirements.txt
    # At the moment this check will always fail due to multiple known limitations, ignore result
    - ${IDF_PATH}/tools/ci/multirun_with_pyenv.sh -p 3.6.10 ./build_docs.py -l $DOCLANG -t $DOCTGT linkcheck || { echo "THERE ARE ISSUES DUE TO KNOWN LIMITATIONS, PLEASE FIX THEM. Nowadays we're ignored them to pass pipeline."; true; }

check_doc_links_en_esp32:
  extends: .check_doc_links_template
  variables:
    DOCLANG: "en"
    DOCTGT: "esp32"

check_doc_links_en_esp32s2:
  extends: .check_doc_links_template
  variables:
    DOCLANG: "en"
    DOCTGT: "esp32s2"

check_doc_links_zh_CN_esp32:
  extends: .check_doc_links_template
  variables:
    DOCLANG: "zh_CN"
    DOCTGT: "esp32"

check_doc_links_zh_CN_esp32s2:
  extends: .check_doc_links_template
  variables:
    DOCLANG: "zh_CN"
    DOCTGT: "esp32s2"
